./localHeadlessSingle.sh scenarioBiasFactorSensitivity5 scenarioBiasFactorSensitivity-2-1
./localHeadlessSingle.sh scenarioBiasFactorSensitivity6 scenarioBiasFactorSensitivity-2-2
./localHeadlessSingle.sh scenarioBiasFactorSensitivity7 scenarioBiasFactorSensitivity-2-3
./localHeadlessSingle.sh scenarioBiasFactorSensitivity8 scenarioBiasFactorSensitivity-2-4
./localHeadlessSingle.sh scenarioBiasFactorSensitivity9 scenarioBiasFactorSensitivity-3-1
./localHeadlessSingle.sh scenarioBiasFactorSensitivity10 scenarioBiasFactorSensitivity-3-2
./localHeadlessSingle.sh scenarioBiasFactorSensitivity11 scenarioBiasFactorSensitivity-3-3
./localHeadlessSingle.sh scenarioBiasFactorSensitivity12 scenarioBiasFactorSensitivity-3-4
./localHeadlessSingle.sh scenarioBiasFactorSensitivity13 scenarioBiasFactorSensitivity-4-1
./localHeadlessSingle.sh scenarioBiasFactorSensitivity14 scenarioBiasFactorSensitivity-4-2
./localHeadlessSingle.sh scenarioBiasFactorSensitivity15 scenarioBiasFactorSensitivity-4-3
./localHeadlessSingle.sh scenarioBiasFactorSensitivity16 scenarioBiasFactorSensitivity-4-4
./localHeadlessSingle.sh scenarioBiasFactorSensitivity17 scenarioBiasFactorSensitivity-5-1
./localHeadlessSingle.sh scenarioBiasFactorSensitivity18 scenarioBiasFactorSensitivity-5-2
./localHeadlessSingle.sh scenarioBiasFactorSensitivity19 scenarioBiasFactorSensitivity-5-3
./localHeadlessSingle.sh scenarioBiasFactorSensitivity20 scenarioBiasFactorSensitivity-5-4

